version: "3.9"
services:
  # postgres db
  system-db:
    container_name: system-db
    build:
      context: .
      dockerfile: deploy/dockerFiles/Dockerfile-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  # redis
  redis-cache:
    container_name: redis-cache
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "yourpassword" ]


  # blobs
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./azurite:/data


  # server
  tukano-app:
    container_name: tukano-app
    depends_on:
      system-db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      azurite:
        condition: service_started
    build:
      context: .
      dockerfile: deploy/dockerFiles/Dockerfile-tukano
    environment:
      - REDIS_HOSTNAME=localhost
      - REDIS_KEY=password
    ports:
      - "8080:8080"
