# 1st stage: copy de code and dependencies and build the project
FROM maven:3.8.8-eclipse-temurin-17 AS BUILDER_IMAGE

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# 2nd stage: deploy the apk
FROM tomcat:10.0-jdk17

# Set the working directory in the container
WORKDIR /usr/local/tomcat

# Copy the WAR file from the Maven build
COPY --from=BUILDER_IMAGE /app/target/*.war ./webapps/

# Expose the default Tomcat port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
