apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-app
  labels:
    app: tukano-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-app
  template:
    metadata:
      labels:
        app: tukano-app
    spec:
      containers:

        # TUKANO APK
        - name: tukano-app
          image: sideghost/tukano-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOSTNAME
              value: "localhost"
            - name: REDIS_KEY
              value: "password"

        # Postgres DB
        - name: postgres
          image: sideghost/postgres
          ports:
            - containerPort: 5432
          env:
              - name: POSTGRES_PASSWORD
                value: "postgres"
          volumeMounts:
              - mountPath: /var/lib/postgresql/data
                name: postgres-data

        # blob storage
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite
          ports:
            - containerPort: 10000
          args: ["azurite-blob", "--blobHost", "0.0.0.0"]

        # REDIS CACHE
        - name: redis
          image: redis/redis-stack-server:latest
          ports:
            - containerPort: 6379
          args: [ "redis-server", "--requirepass", "password" ]
          env:
            - name: REDIS_PASSWORD
              value: "password"


      volumes:
        - name: postgres-data
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: tukano-app-service
spec:
  selector:
    app: tukano-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
